// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions? get maybeCurrentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return null;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      default:
        return null;
    }
  }

  static FirebaseOptions get currentPlatform =>
      maybeCurrentPlatform ??
      (throw UnsupportedError(
        'Firebase has not been configured for this platform. Run '
        '`flutterfire configure` before enabling Firebase features.',
      ));

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV2pIvLegb8vsVXSPeYDrzVGC_ROxoCEk',
    appId: '1:548355194702:ios:60915c7a5548644b69e81f',
    messagingSenderId: '548355194702',
    projectId: 'smartcanteen-8fe8c',
    storageBucket: 'smartcanteen-8fe8c.firebasestorage.app',
    iosBundleId: 'vn.edu.huflit.smartcanteen',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8sKqpUWza2Nu_g6X1yIHEK4--DtI_LN8',
    appId: '1:548355194702:web:1916673dddcd954969e81f',
    messagingSenderId: '548355194702',
    projectId: 'smartcanteen-8fe8c',
    authDomain: 'smartcanteen-8fe8c.firebaseapp.com',
    storageBucket: 'smartcanteen-8fe8c.firebasestorage.app',
    measurementId: 'G-60YBDEJ49Q',
  );
}
